dubbo:
  application:
    name: service-product
    qos-enable: true
    qos-port: 33331
    qos-accept-foreign-ip: false
  registry:
    protocol: zookeeper
    address: 154.8.211.233:2181
  protocol:
    port: 28819
  provider:
    timeout: 20000
spring:
  datasource:
    url: jdbc:mysql:///jxzshop?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
  configuration:
    #Mybatis会在控制台打印执行的sql语句 - 可以配合mybatis log插件使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 1995
